### ISSUE TITLE
GitHub Workflows as deployment?

### ISSUE THREAD

**Issue by consideRatio** [henchbot/mybinder.org-upgrades#6]
How do you feel about letting the deployment of henchbot be transformed to run in GitHub Workflows that could be triggered manually, as a cron job, and through a webhook?

**Comment by henchc** [comment]
Sorry, I haven't worked with Workflows before. Is that compatible with Heroku? That's how it is set up now (https://github.com/henchbot/mybinder.org-upgrades/deployments/activity_log?environment=ancient-chamber-80926)

I'd be happy to add it, is there a tutorial I can follow? https://github.com/marketplace/actions/deploy-to-heroku ?

**Comment by consideRatio** [comment]
No worries I'll try to clarify this a bit!

I meant that instead of using Heroku at all, that we would run this script entirely using GitHub's CI system. Practically, it would mean to defining a GitHub Workflow .yaml file in the .github/workflows folder with a set of instructions on what and when to run some code.

If you are interested in doing such transition, I'd love to help you in any way I can, for example by providing quick feedback on your github workflow file. I don't think there will be any need to change the henchbot code itself.

## Example workflow

Below is an example GitHub Workflow file which could be for example .github/workflows/workflow1.yaml in this repo.

```yaml
# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
---
name: Example workflow

# run this workflow on...
# - cron schedule
# - manual dispatch through GitHub UI button, 
# - ... more options available, such as to trigger by
#   other workflows in binderhub and repo2docker etc.
on:
  schedule:
    # At 00:00 - https://crontab.guru
    - cron: "0 0 * * *"
  workflow_dispatch:

# each workflow contains jobs to run
jobs:
  job1-of-workflow:
    runs-on: ubuntu-20.04

    # each job contains steps to execute
    # - our two first steps refer to predefined "actions"
    # - the other steps are running arbitrary shell scripts
    steps:
      # action to make the github repository available in the current working directory
      - uses: actions/checkout@v2
        with:
          # ensures we get full git repo history
          fetch-depth: 0

      # action to make python available
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install python stuff
        run: |
          pip install -r requirements.txt

      - name: Run python stuff
        env:
          # secrets.HENCHBOT_TOKEN set in GitHub's UI
          # https://github.com/henchbot/mybinder.org-upgrades/settings/secrets/actions
          HENCHBOT_TOKEN=${{ secrets.HENCHBOT_TOKEN }}
        run: |
          python bin/update
```

## Other examples
- Workflow definitions in z2jh: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/.github/workflows
- Workflow status in z2jh: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/actions
- GitHub docs on workflows: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
